# brew install vhs
Output demo.gif

Set FontSize 19
Set Width 1200
Set Height 450

Hide
Type "export PS1='$ '" Enter
Ctrl+L
Show

Sleep 500ms

Type "ls"

Sleep 500ms

Enter

Sleep 500ms

Type "cat data.yaml | yq"

Sleep 500ms

Enter

Sleep 500ms

Type "pypdfform --need-appearances fill sample_template.pdf -f data.yaml -o output.pdf"

Sleep 500ms

Enter

Sleep 350ms

Type "ls"

Sleep 500ms

Enter

Sleep 5s
